import { CommissionOrder, NotificationItem, PrdOpenIssues, WorkflowNodeInfo } from './types';

export const INITIAL_NODE_INFOS: WorkflowNodeInfo[] = [
  {
    id: 'sample_receiving',
    name: '委托收样',
    code: 'STEP_01',
    step: 1,
    description: '客户委托与样品现场验收，核对规格数量并赋码',
    pendingCount: 0,
    iconName: 'PackageCheck',
  },
  {
    id: 'fee_collection',
    name: '检测收费',
    code: 'STEP_02',
    step: 2,
    description: '根据项目标准核定费用，财务收款开据凭证',
    pendingCount: 22004,
    iconName: 'Receipt',
  },
  {
    id: 'task_assignment',
    name: '任务分配',
    code: 'STEP_03',
    step: 3,
    description: '检测任务指派，匹配设备资质与检测人员计划',
    pendingCount: 27,
    iconName: 'UserCheck',
  },
  {
    id: 'testing',
    name: '试验检测',
    code: 'STEP_04',
    step: 4,
    description: '标准物理/化学试验操作，原始数据录入与公式自算',
    pendingCount: 4510,
    iconName: 'FlaskConical',
  },
  {
    id: 'review',
    name: '复核确认',
    code: 'STEP_05',
    step: 5,
    description: '双人复核试验数据真实性、公式运算与评定标准',
    pendingCount: 0,
    iconName: 'FileCheck2',
  },
  {
    id: 'report_audit',
    name: '报告审核',
    code: 'STEP_06',
    step: 6,
    description: '检测报告技术审查与格式校核，确保规范合规',
    pendingCount: 187,
    iconName: 'ShieldCheck',
  },
  {
    id: 'report_approval',
    name: '报告批准',
    code: 'STEP_07',
    step: 7,
    description: '授权签字人签批批准，确立检测报告法律效力',
    pendingCount: 99,
    iconName: 'Award',
  },
  {
    id: 'report_print',
    name: '报告打印',
    code: 'STEP_08',
    step: 8,
    description: '正式防伪打印，套印CMA/CNAS专用章与归档',
    pendingCount: 1205,
    iconName: 'Printer',
  },
  {
    id: 'report_delivery',
    name: '报告领取',
    code: 'STEP_09',
    step: 9,
    description: '客户现场签署凭据或顺丰寄件，达成业务闭环',
    pendingCount: 15377,
    iconName: 'Truck',
  },
];

export const INITIAL_ORDERS: CommissionOrder[] = [
  // 1. WT001: Currently at Task Assignment (任务分配)
  {
    id: 'order-001',
    orderCode: 'WT001',
    clientName: '中建华东工程建设发展有限公司',
    contactPerson: '张工',
    contactPhone: '13812345678',
    orderDate: '2026-09-05',
    testType: '见证取样检验',
    projectTitle: '东方金融科技大厦地基及主体工程',
    receivableAmount: 5000,
    paidAmount: 5000,
    unpaidAmount: 0,
    feeStatus: '已收费',
    paymentMethod: '公对公银行转账',
    invoiceTitle: '中建华东工程建设发展有限公司 (91310000XXXXXX)',
    currentStep: 'task_assignment',
    overallStatus: 'PROCESSING',
    samples: [
      {
        id: 's-001',
        sampleCode: 'S001',
        sampleName: '混凝土立方体抗压试块',
        specModel: '150×150×150 mm (C30)',
        quantity: 3,
        unit: '组',
        status: '已收样',
        barcode: 'BC20260905001',
        location: '标养室 A-04 架',
      },
      {
        id: 's-002',
        sampleCode: 'S002',
        sampleName: '热轧带肋钢筋',
        specModel: 'HRB400E Φ18 mm',
        quantity: 3,
        unit: '根',
        status: '已收样',
        barcode: 'BC20260905002',
        location: '力学样品暂存区 B-02',
      },
    ],
    testProjects: [
      {
        id: 'tp-001',
        projectName: '混凝土抗压强度试验',
        testStandard: 'GB/T 50081-2019',
        unitPrice: 500,
        quantity: 4,
        totalAmount: 2000,
      },
      {
        id: 'tp-002',
        projectName: '钢筋拉伸及弯曲性能试验',
        testStandard: 'GB/T 28900-2022',
        unitPrice: 600,
        quantity: 5,
        totalAmount: 3000,
      },
    ],
    tasks: [
      {
        id: 'task-001',
        taskCode: 'T001',
        orderCode: 'WT001',
        clientName: '中建华东工程建设发展有限公司',
        sampleCode: 'S001',
        sampleName: '混凝土立方体抗压试块',
        testProject: '混凝土抗压强度试验',
        standard: 'GB/T 50081-2019',
        priority: '加急',
        status: '待分配',
      },
      {
        id: 'task-002',
        taskCode: 'T002',
        orderCode: 'WT001',
        clientName: '中建华东工程建设发展有限公司',
        sampleCode: 'S002',
        sampleName: '热轧带肋钢筋',
        testProject: '钢筋拉伸及弯曲性能试验',
        standard: 'GB/T 28900-2022',
        priority: '普通',
        status: '待分配',
      },
    ],
    history: [
      {
        id: 'h-01',
        nodeId: 'sample_receiving',
        nodeName: '委托收样',
        operator: '张秀丽',
        operatorRole: '收样员',
        action: '完成收样，核查试块无破损，贴赋条形码',
        timestamp: '2026-09-05 09:15:00',
        status: 'COMPLETED',
      },
      {
        id: 'h-02',
        nodeId: 'fee_collection',
        nodeName: '检测收费',
        operator: '李梅',
        operatorRole: '财务收费员',
        action: '已收到工程公账转账 ¥5,000 元，开据收费凭证 No.20260905-09',
        timestamp: '2026-09-05 10:30:20',
        status: 'COMPLETED',
      },
    ],
  },

  // 2. WT002: Currently at Fee Collection (检测收费 待收费)
  {
    id: 'order-002',
    orderCode: 'WT002',
    clientName: '宏业交通路桥工程建设集团',
    contactPerson: '王总监',
    contactPhone: '13988776655',
    orderDate: '2026-09-05',
    testType: '市政工程监督检测',
    projectTitle: '沿江高速三期跨线桥立交工程',
    receivableAmount: 3200,
    paidAmount: 0,
    unpaidAmount: 3200,
    feeStatus: '待收费',
    currentStep: 'fee_collection',
    overallStatus: 'PENDING',
    samples: [
      {
        id: 's-003',
        sampleCode: 'S003',
        sampleName: '高性能沥青混凝土',
        specModel: 'SMA-13',
        quantity: 2,
        unit: '组',
        status: '已收样',
        barcode: 'BC20260905003',
        location: '沥青室 01 号储藏柜',
      },
    ],
    testProjects: [
      {
        id: 'tp-003',
        projectName: '沥青混合料马歇尔稳定度试验',
        testStandard: 'JTG E20-2011',
        unitPrice: 1600,
        quantity: 2,
        totalAmount: 3200,
      },
    ],
    tasks: [],
    history: [
      {
        id: 'h-03',
        nodeId: 'sample_receiving',
        nodeName: '委托收样',
        operator: '张秀丽',
        operatorRole: '收样员',
        action: '委托录入并确认收样，样品已送检温控区',
        timestamp: '2026-09-05 11:20:00',
        status: 'COMPLETED',
      },
    ],
  },

  // 3. WT003: Currently at Testing (试验检测中)
  {
    id: 'order-003',
    orderCode: 'WT003',
    clientName: '上海建工第一建筑集团',
    contactPerson: '李工',
    contactPhone: '13700011223',
    orderDate: '2026-09-04',
    testType: '商砼出厂复验',
    projectTitle: '徐汇滨江智慧绿岛研发中心',
    receivableAmount: 4800,
    paidAmount: 4800,
    unpaidAmount: 0,
    feeStatus: '已收费',
    paymentMethod: '企业网银转账',
    currentStep: 'testing',
    overallStatus: 'PROCESSING',
    samples: [
      {
        id: 's-004',
        sampleCode: 'S004',
        sampleName: '抗渗混凝土试块',
        specModel: 'P8 C35 175×185×150 mm',
        quantity: 6,
        unit: '块',
        status: '检测中',
        barcode: 'BC20260904001',
      },
    ],
    testProjects: [
      {
        id: 'tp-004',
        projectName: '混凝土抗渗性能试验 (逐级加压法)',
        testStandard: 'GB/T 50082-2009',
        unitPrice: 800,
        quantity: 6,
        totalAmount: 4800,
      },
    ],
    tasks: [
      {
        id: 'task-003',
        taskCode: 'T003',
        orderCode: 'WT003',
        clientName: '上海建工第一建筑集团',
        sampleCode: 'S004',
        sampleName: '抗渗混凝土试块',
        testProject: '混凝土抗渗性能试验',
        standard: 'GB/T 50082-2009',
        assigneeName: '陈建国 (高级力学工程师)',
        equipment: 'HP-4.0型微机控制自动加压抗渗仪 (检定证书有效期至2027-03)',
        planDate: '2026-09-06',
        priority: '特急',
        status: '待检测',
        assignedTime: '2026-09-04 15:40:00',
        testData: {
          specimen1Area: 22500,
          specimen1Load: 785.4,
          specimen2Area: 22500,
          specimen2Load: 792.1,
          specimen3Area: 22500,
          specimen3Load: 778.6,
          designGrade: 'C35 (P8)',
          verdict: '待评定',
          testEquipment: 'HP-4.0型抗渗仪',
          temperature: '20.5℃',
          humidity: '96%',
        },
      },
    ],
    history: [
      {
        id: 'h-04',
        nodeId: 'sample_receiving',
        nodeName: '委托收样',
        operator: '张秀丽',
        operatorRole: '收样员',
        action: '完成样品查验与登记',
        timestamp: '2026-09-04 10:00:00',
        status: 'COMPLETED',
      },
      {
        id: 'h-05',
        nodeId: 'fee_collection',
        nodeName: '检测收费',
        operator: '李梅',
        operatorRole: '财务收费员',
        action: '确认全额到账 ¥4,800',
        timestamp: '2026-09-04 11:15:00',
        status: 'COMPLETED',
      },
      {
        id: 'h-06',
        nodeId: 'task_assignment',
        nodeName: '任务分配',
        operator: '周主任',
        operatorRole: '调度主任',
        action: '指定由高级工程师陈建国主检，设备已校验就绪',
        timestamp: '2026-09-04 15:40:00',
        status: 'COMPLETED',
      },
    ],
  },

  // 4. WT004: Currently at Review (复核确认 待复核)
  {
    id: 'order-004',
    orderCode: 'WT004',
    clientName: '中铁二十局基础设施发展公司',
    contactPerson: '周经理',
    contactPhone: '13611223344',
    orderDate: '2026-09-03',
    testType: '第三方见证试验',
    projectTitle: '轨道交通18号线二期地下车站隧道盾构段',
    receivableAmount: 3600,
    paidAmount: 3600,
    unpaidAmount: 0,
    feeStatus: '已收费',
    currentStep: 'review',
    overallStatus: 'PROCESSING',
    samples: [
      {
        id: 's-005',
        sampleCode: 'S005',
        sampleName: '盾构管片混凝土试块 (同条件养护)',
        specModel: '150×150×150 mm (C50)',
        quantity: 3,
        unit: '组',
        status: '检测中',
        barcode: 'BC20260903001',
      },
    ],
    testProjects: [
      {
        id: 'tp-005',
        projectName: '混凝土立方体抗压强度试验',
        testStandard: 'GB/T 50081-2019',
        unitPrice: 1200,
        quantity: 3,
        totalAmount: 3600,
      },
    ],
    tasks: [
      {
        id: 'task-004',
        taskCode: 'T004',
        orderCode: 'WT004',
        clientName: '中铁二十局基础设施发展公司',
        sampleCode: 'S005',
        sampleName: '盾构管片混凝土试块',
        testProject: '混凝土立方体抗压强度试验',
        standard: 'GB/T 50081-2019',
        assigneeName: '张三 (力学主检员)',
        equipment: 'YAW-3000微机控制电液伺服压力试验机',
        planDate: '2026-09-04',
        priority: '加急',
        status: '待复核',
        assignedTime: '2026-09-03 14:00:00',
        submitTime: '2026-09-04 16:30:00',
        testData: {
          specimen1Area: 22500,
          specimen1Load: 1238.5, // 55.04 MPa
          specimen2Area: 22500,
          specimen2Load: 1251.2, // 55.61 MPa
          specimen3Area: 22500,
          specimen3Load: 1244.0, // 55.29 MPa
          strength1: 55.0,
          strength2: 55.6,
          strength3: 55.3,
          averageStrength: 55.3,
          designGrade: 'C50',
          verdict: '合格',
          testEquipment: 'YAW-3000微机压力机',
          temperature: '20.0℃',
          humidity: '95%',
        },
      },
    ],
    history: [
      {
        id: 'h-07',
        nodeId: 'sample_receiving',
        nodeName: '委托收样',
        operator: '张秀丽',
        operatorRole: '收样员',
        action: '完成样品验收',
        timestamp: '2026-09-03 10:20:00',
        status: 'COMPLETED',
      },
      {
        id: 'h-08',
        nodeId: 'fee_collection',
        nodeName: '检测收费',
        operator: '李梅',
        operatorRole: '财务收费员',
        action: '收费 ¥3,600 完成',
        timestamp: '2026-09-03 11:30:00',
        status: 'COMPLETED',
      },
      {
        id: 'h-09',
        nodeId: 'task_assignment',
        nodeName: '任务分配',
        operator: '周主任',
        operatorRole: '调度主任',
        action: '任务分配给主检员张三',
        timestamp: '2026-09-03 14:00:00',
        status: 'COMPLETED',
      },
      {
        id: 'h-10',
        nodeId: 'testing',
        nodeName: '试验检测',
        operator: '张三',
        operatorRole: '主检检测工程师',
        action: '完成压力机加荷破坏试验，自动采集并计算强度代表值 55.3 MPa (评定合格)，提交复核',
        timestamp: '2026-09-04 16:30:00',
        status: 'COMPLETED',
      },
    ],
  },

  // 5. WT005: Currently at Report Audit (报告审核 待审核)
  {
    id: 'order-005',
    orderCode: 'WT005',
    clientName: '保利置业集团有限公司',
    contactPerson: '郑主管',
    contactPhone: '13566778899',
    orderDate: '2026-09-02',
    testType: '建筑工程主体结构复验',
    projectTitle: '保利天悦湾三期 6# 楼顶板',
    receivableAmount: 2400,
    paidAmount: 2400,
    unpaidAmount: 0,
    feeStatus: '已收费',
    currentStep: 'report_audit',
    overallStatus: 'PROCESSING',
    samples: [
      {
        id: 's-006',
        sampleCode: 'S006',
        sampleName: '商品混凝土试块',
        specModel: '150×150×150 mm (C30)',
        quantity: 3,
        unit: '组',
        status: '已完成',
        barcode: 'BC20260902001',
      },
    ],
    testProjects: [
      {
        id: 'tp-006',
        projectName: '混凝土立方体抗压强度',
        testStandard: 'GB/T 50081-2019',
        unitPrice: 800,
        quantity: 3,
        totalAmount: 2400,
      },
    ],
    tasks: [
      {
        id: 'task-005',
        taskCode: 'T005',
        orderCode: 'WT005',
        clientName: '保利置业集团有限公司',
        sampleCode: 'S006',
        sampleName: '商品混凝土试块',
        testProject: '混凝土立方体抗压强度',
        standard: 'GB/T 50081-2019',
        assigneeName: '赵六 (检测工程师)',
        equipment: 'YAW-2000伺服压力机',
        priority: '普通',
        status: '已复核',
        submitTime: '2026-09-03 15:00:00',
        reviewerName: '孙复核 (技术复核员)',
        reviewTime: '2026-09-04 10:00:00',
        reviewComment: '经双人校对，破坏荷载与加荷速率符合GB/T 50081规范，数据真实有效，同意出具报告。',
        testData: {
          specimen1Area: 22500,
          specimen1Load: 780.0,
          specimen2Area: 22500,
          specimen2Load: 795.0,
          specimen3Area: 22500,
          specimen3Load: 788.0,
          strength1: 34.7,
          strength2: 35.3,
          strength3: 35.0,
          averageStrength: 35.0,
          designGrade: 'C30',
          verdict: '合格',
          testEquipment: 'YAW-2000伺服压力机',
          temperature: '21.0℃',
          humidity: '95%',
        },
      },
    ],
    report: {
      id: 'rep-001',
      reportCode: 'BG001',
      orderCode: 'WT005',
      taskCodes: ['T005'],
      clientName: '保利置业集团有限公司',
      sampleName: '商品混凝土试块 (150×150×150mm)',
      testCategory: '建筑工程主体结构检测',
      testProject: '混凝土抗压强度检测',
      summaryData: '设计强度等级 C30，28d标养抗压强度代表值 35.0 MPa (达到设计强度的 116.7%)',
      conclusion: '该组混凝土立方体抗压试块经检验，其抗压强度代表值为 35.0 MPa，符合设计等级 C30 及 GB 50107-2010 标准技术要求，综合判定合格。',
      status: '待审核',
      printCopies: 2,
      printedCopies: 0,
      printCount: 0,
    },
    history: [
      {
        id: 'h-11',
        nodeId: 'sample_receiving',
        nodeName: '委托收样',
        operator: '张秀丽',
        operatorRole: '收样员',
        action: '完成收样与入库',
        timestamp: '2026-09-02 09:30:00',
        status: 'COMPLETED',
      },
      {
        id: 'h-12',
        nodeId: 'fee_collection',
        nodeName: '检测收费',
        operator: '李梅',
        operatorRole: '财务收费员',
        action: '实收金额 ¥2,400',
        timestamp: '2026-09-02 10:20:00',
        status: 'COMPLETED',
      },
      {
        id: 'h-13',
        nodeId: 'task_assignment',
        nodeName: '任务分配',
        operator: '周主任',
        operatorRole: '调度主任',
        action: '分派任务给赵六',
        timestamp: '2026-09-02 11:00:00',
        status: 'COMPLETED',
      },
      {
        id: 'h-14',
        nodeId: 'testing',
        nodeName: '试验检测',
        operator: '赵六',
        operatorRole: '检测工程师',
        action: '试验完成，自动生成试验记录',
        timestamp: '2026-09-03 15:00:00',
        status: 'COMPLETED',
      },
      {
        id: 'h-15',
        nodeId: 'review',
        nodeName: '复核确认',
        operator: '孙复核',
        operatorRole: '技术复核员',
        action: '复核通过，生成正式检测报告 BG001 并提交审核',
        timestamp: '2026-09-04 10:00:00',
        status: 'COMPLETED',
      },
    ],
  },

  // 6. WT006: Currently at Report Approval (报告批准 待批准)
  {
    id: 'order-006',
    orderCode: 'WT006',
    clientName: '华润置地（华东）开发运营有限公司',
    contactPerson: '钱工',
    contactPhone: '13911112222',
    orderDate: '2026-09-01',
    testType: '地基承载力静载试验',
    projectTitle: '华润万象城地下基坑连续墙及桩基',
    receivableAmount: 8500,
    paidAmount: 8500,
    unpaidAmount: 0,
    feeStatus: '已收费',
    currentStep: 'report_approval',
    overallStatus: 'PROCESSING',
    samples: [
      {
        id: 's-007',
        sampleCode: 'S007',
        sampleName: '预制管桩 (PHC 500 AB 125)',
        specModel: 'Φ500 mm 壁厚 125 mm',
        quantity: 2,
        unit: '根',
        status: '已完成',
      },
    ],
    testProjects: [
      {
        id: 'tp-007',
        projectName: '单桩竖向抗压静载试验',
        testStandard: 'JGJ 106-2014',
        unitPrice: 8500,
        quantity: 1,
        totalAmount: 8500,
      },
    ],
    tasks: [],
    report: {
      id: 'rep-002',
      reportCode: 'BG002',
      orderCode: 'WT006',
      taskCodes: ['T006'],
      clientName: '华润置地（华东）开发运营有限公司',
      sampleName: '工程基桩单桩竖向抗压静载荷试验 (2根试验桩)',
      testCategory: '地基基础工程专业检测',
      testProject: '单桩竖向抗压极限承载力',
      summaryData: '最大试验荷载 3200 kN，累计沉降量 18.24 mm，回弹率 82.5%',
      conclusion: '经现场单桩竖向静载荷试验测试，1#与2#试验桩在最大荷载3200kN作用下未出现破坏极限状态，单桩竖向抗压特征值满足设计要求 (Ra≥1600kN)。',
      status: '待批准',
      auditorName: '吴审核 (技术质量部主任)',
      auditTime: '2026-09-04 14:20:00',
      auditComment: '荷载分级加压及沉降稳定观测曲线标准规范，计算数据准确，审核通过，呈报授权签字人批准。',
      printCopies: 3,
      printedCopies: 0,
      printCount: 0,
    },
    history: [
      {
        id: 'h-16',
        nodeId: 'sample_receiving',
        nodeName: '委托收样',
        operator: '张秀丽',
        operatorRole: '收样员',
        action: '现场工程见证登记',
        timestamp: '2026-09-01 09:00:00',
        status: 'COMPLETED',
      },
      {
        id: 'h-17',
        nodeId: 'fee_collection',
        nodeName: '检测收费',
        operator: '李梅',
        operatorRole: '财务收费员',
        action: '收款核验完成',
        timestamp: '2026-09-01 10:00:00',
        status: 'COMPLETED',
      },
      {
        id: 'h-18',
        nodeId: 'task_assignment',
        nodeName: '任务分配',
        operator: '周主任',
        operatorRole: '调度主任',
        action: '指派地基检测团队进场',
        timestamp: '2026-09-01 10:30:00',
        status: 'COMPLETED',
      },
      {
        id: 'h-19',
        nodeId: 'testing',
        nodeName: '试验检测',
        operator: '何工 (岩土力学检测师)',
        operatorRole: '检测工程师',
        action: '试验数据上传并完成复核',
        timestamp: '2026-09-03 17:00:00',
        status: 'COMPLETED',
      },
      {
        id: 'h-20',
        nodeId: 'review',
        nodeName: '复核确认',
        operator: '孙复核',
        operatorRole: '技术复核员',
        action: '数据曲线核验完毕',
        timestamp: '2026-09-04 09:10:00',
        status: 'COMPLETED',
      },
      {
        id: 'h-21',
        nodeId: 'report_audit',
        nodeName: '报告审核',
        operator: '吴审核',
        operatorRole: '技术质量部主任',
        action: '审核通过，呈批授权签字人',
        timestamp: '2026-09-04 14:20:00',
        status: 'COMPLETED',
      },
    ],
  },

  // 7. WT007: Currently at Report Print (报告打印 待打印)
  {
    id: 'order-007',
    orderCode: 'WT007',
    clientName: '中交第二公路工程局',
    contactPerson: '黄工',
    contactPhone: '13822334455',
    orderDate: '2026-08-31',
    testType: '公路路基路面材料检测',
    projectTitle: 'S20外环线改建提升工程04标',
    receivableAmount: 1800,
    paidAmount: 1800,
    unpaidAmount: 0,
    feeStatus: '已收费',
    currentStep: 'report_print',
    overallStatus: 'PROCESSING',
    samples: [
      {
        id: 's-008',
        sampleCode: 'S008',
        sampleName: '无机结合料稳定碎石 (基层)',
        specModel: '水泥稳定碎石 (4%水泥剂量)',
        quantity: 6,
        unit: '个',
        status: '已完成',
      },
    ],
    testProjects: [
      {
        id: 'tp-008',
        projectName: '无侧限抗压强度试验 (7d龄期)',
        testStandard: 'JTG E51-2009',
        unitPrice: 300,
        quantity: 6,
        totalAmount: 1800,
      },
    ],
    tasks: [],
    report: {
      id: 'rep-003',
      reportCode: 'BG003',
      orderCode: 'WT007',
      taskCodes: ['T007'],
      clientName: '中交第二公路工程局',
      sampleName: '水泥稳定碎石圆柱体试件 (Φ150×150mm)',
      testCategory: '公路工程无机结合料检测',
      testProject: '7d浸水无侧限抗压强度',
      summaryData: 'Rc = 4.8 MPa, 变异系数 Cv = 6.2%, 代表值满足设计要求',
      conclusion: '经检测，该组水泥稳定碎石7d浸水无侧限抗压强度满足设计技术指标要求 (Rc≥4.0MPa)，判定合格。',
      status: '待打印',
      auditorName: '吴审核',
      auditTime: '2026-09-04 09:30:00',
      approverName: '马总工 (授权签字人)',
      approveTime: '2026-09-05 08:45:00',
      approveComment: '同意签发正式检测报告，加盖CMA专用章。',
      printCopies: 2,
      printedCopies: 0,
      printCount: 0,
    },
    history: [
      {
        id: 'h-22',
        nodeId: 'report_approval',
        nodeName: '报告批准',
        operator: '马总工',
        operatorRole: '授权签字人',
        action: '完成电子签名授权签发',
        timestamp: '2026-09-05 08:45:00',
        status: 'COMPLETED',
      },
    ],
  },

  // 8. WT008: Currently at Report Delivery (报告领取 待领取)
  {
    id: 'order-008',
    orderCode: 'WT008',
    clientName: '万科企业股份有限公司',
    contactPerson: '赵经理',
    contactPhone: '13900223344',
    orderDate: '2026-08-30',
    testType: '建筑门窗三性检测',
    projectTitle: '万科朗拾花语住宅小区一期',
    receivableAmount: 3800,
    paidAmount: 3800,
    unpaidAmount: 0,
    feeStatus: '已收费',
    currentStep: 'report_delivery',
    overallStatus: 'PROCESSING',
    samples: [
      {
        id: 's-009',
        sampleCode: 'S009',
        sampleName: '铝合金断桥隔热平开窗',
        specModel: '1500×1800 mm 5+12A+5 中空玻璃',
        quantity: 3,
        unit: '樘',
        status: '已完成',
      },
    ],
    testProjects: [
      {
        id: 'tp-009',
        projectName: '门窗气密、水密、抗风压性能检测',
        testStandard: 'GB/T 7106-2019',
        unitPrice: 3800,
        quantity: 1,
        totalAmount: 3800,
      },
    ],
    tasks: [],
    report: {
      id: 'rep-004',
      reportCode: 'BG004',
      orderCode: 'WT008',
      taskCodes: ['T008'],
      clientName: '万科企业股份有限公司',
      sampleName: '铝合金隔热平开窗 (三性测试)',
      testCategory: '建筑物理性能检测',
      testProject: '气密性、水密性、抗风压性能',
      summaryData: '抗风压达9级 (P3=5.0kPa)，水密达6级 (700Pa)，气密达8级 (q1=0.5m³/(m·h))',
      conclusion: '样品门窗气密性、水密性及抗风压物理性能均满足规范及设计指标，判定合格。',
      status: '待领取',
      auditorName: '吴审核',
      auditTime: '2026-09-03 16:00:00',
      approverName: '马总工',
      approveTime: '2026-09-04 09:00:00',
      printCopies: 2,
      printedCopies: 2,
      printerName: '刘打印 (档案打印员)',
      printTime: '2026-09-04 10:15:00',
      printCount: 1,
    },
    history: [
      {
        id: 'h-23',
        nodeId: 'report_print',
        nodeName: '报告打印',
        operator: '刘打印',
        operatorRole: '档案打印员',
        action: '完成正式套打与防伪烫印，已移交服务大厅待客户领取',
        timestamp: '2026-09-04 10:15:00',
        status: 'COMPLETED',
      },
    ],
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'n-01',
    type: 'TASK_ASSIGNED',
    title: '新的检测任务待处理',
    content: '任务编号 T001 (混凝土抗压强度试验) 已分配给您，请尽快安排试验。',
    time: '10 分钟前',
    read: false,
    orderCode: 'WT001',
    nodeId: 'testing',
  },
  {
    id: 'n-02',
    type: 'TEST_SUBMITTED',
    title: '检测任务已提交复核',
    content: '检测任务 T004 (盾构管片混凝土试块) 已由张三提交，请及时进行技术复核。',
    time: '25 分钟前',
    read: false,
    orderCode: 'WT004',
    nodeId: 'review',
  },
  {
    id: 'n-03',
    type: 'REPORT_APPROVED',
    title: '报告已批准可打印',
    content: '报告 BG003 (S20外环线水稳碎石) 已由马总工批准签发，请安排报告套打。',
    time: '1 小时前',
    read: false,
    orderCode: 'WT007',
    nodeId: 'report_print',
  },
  {
    id: 'n-04',
    type: 'INFO',
    title: '收费到账提醒',
    content: '委托单 WT001 检测费用 ¥5,000 已全额核销，可进行检测调度派工。',
    time: '2 小时前',
    read: true,
    orderCode: 'WT001',
    nodeId: 'task_assignment',
  },
];

export const DEFAULT_PRD_ISSUES: PrdOpenIssues = {
  allowAssignBeforePaid: false,       // 甲方待确认: 是否允许未收费直接进入任务分配 (默认否，可开关切换模拟)
  allowSplitMultipleTasks: true,      // 甲方待确认: 一个委托是否允许拆成多个检测任务 (支持拆单)
  rejectToNode: 'TESTING',            // 甲方待确认: 复核/审核退回到哪个节点 (默认退回试验检测，也可切退回上一节点)
  allowModifyAfterApproved: false,    // 甲方待确认: 报告批准后是否允许修改 (默认不允许，需走作废重开)
  supportDigitalDelivery: true,       // 甲方待确认: 报告领取是否支持邮寄/电子报告
  statScopeMode: 'PENDING_ONLY',      // 甲方待确认: 首页9个数字统计口径 (当前待办数量)
};
